services:
  backend:
    image: ghcr.io/JumbleJumble/ha-dashboard-backend:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - CONFIG_DIR=/config
      - PORT=5000
    volumes:
      - ./config:/config

  frontend:
    image: ghcr.io/JumbleJumble/ha-dashboard-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
